# Build stage
FROM node:latest

WORKDIR /app

# Copy package.json and package-lock.json
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

RUN npm i --save-dev @types/node

# Copy the rest of the frontend code
COPY frontend/ .

# Build the app
RUN npm run build -- --mode production

# Expose the port
EXPOSE 3000

CMD ["npm", "run", "preview", "--", "--host", "--port", "3000"]