services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      ports:
        - "${FRONTEND_PORT:-80}:80"
      env_file:
        - .env.production
      environment:
        - NODE_ENV=production
      depends_on:
        - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_container
    restart: always
    env_file:
      - .env.production
    ports:
      - "${BACKEND_PRT:-9898}:9797"

  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    env_file:
      - .env.production
    expose:
      - 3306
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mariadb

volumes:
  mariadb_data: