FROM golang:latest

WORKDIR /app

COPY backend/go.mod backend/go.sum ./

RUN go mod download

RUN go install github.com/air-verse/air@latest

COPY backend .

# CMD ["go", "run", "./cmd/server/main.go"]
CMD ["air", "-c", ".air.toml"]
