export enum MusicGenre {
  HIP_HOP = "Hip-Hop",
  RAP = "Rap",
  RNB = "R&B",
  ELECTRONIC = "Electronic",
  DANCE = "Dance",
  SOUL = "Soul",
  FUNK = "Funk",
  DISCO = "Disco",
  ROCK = "Rock",
  POP = "Pop",
  SOUNDTRACK = "Soundtrack",
  LIBRARY = "Library",
  WORLD = "World",
  LATIN = "Latin",
  JAZZ = "Jazz",
  BLUES = "Blues",
  REGGAE = "Reggae",
  DUB = "Dub",
  COUNTRY = "Country",
  FOLK = "Folk",
  CLASSICAL = "Classical",
}
