# k3s/config/secrets-template.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  # Frontend secrets
  FRONTEND_PORT: "80"
  API_URL: "http://backend:9898"
  
  # Backend secrets
  BACKEND_PORT: "9898"
  JWT_SECRET: "example_jwt_secret"
  
  # Database secrets
  MARIADB_ROOT_PASSWORD: "example_root_password"
  MARIADB_PASSWORD: "example_password"
  MARIADB_USER: "dbuser"
  MARIADB_DATABASE: "appdb"

  # Cloudflare secrets
  CLOUDFLARE_TUNNEL_TOKEN: "your_tunnel_token"