apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  # Database secrets
  MARIADB_ROOT_PASSWORD: "example_password"
  MYSQL_DATABASE: "kendodb"
  MYSQL_USER: "kendo"
  MYSQL_PASSWORD: "example_password"
  MYSQL_HOST: "mariadb"  # k3s service name
  MYSQL_PORT: "3306"
  
  # Samples Database Connection
  SAMPLES_DB_USER: "example_user"
  SAMPLES_DB_PASSWORD: "example_password"
  SAMPLES_DB_HOST: "external_host"
  SAMPLES_DB_PORT: "3306"
  SAMPLES_DB_NAME: "ghopper"

  # Application Environment
  NODE_ENV: "production"
  VITE_API_URL: "http://backend:9797"
  BACKEND_PORT: "9797"
  FRONTEND_PORT: "80"
  FRONTEND_URL: "https://your-domain.com/auth-callback"  # Change to your domain

  # Spotify Integration
  SPOTIFY_CLIENT_ID: "your_client_id"
  SPOTIFY_CLIENT_SECRET: "your_client_secret"
  SPOTIFY_REDIRECT_URI: "https://your-domain.com/auth/spotify/callback"  # Change to your domain

  # Security
  JWT_SECRET: "your_production_secret"

  CLOUDFLARE_TUNNEL_TOKEN: "your_tunnel_token"