name: Deploy to K3s

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        id: repo-name
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ env.REPO_LOWER }}/frontend
            ghcr.io/${{ env.REPO_LOWER }}/backend

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: frontend/Dockerfile.prod
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}/frontend:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile.prod
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}/backend:latest
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify kubectl configuration
        run: kubectl get nodes

      - name: Deploy to k3s
        run: |
          # Apply secrets first
          kubectl apply -f k3s/config/secrets.yaml
          
          # Apply all other resources
          kubectl apply -f k3s/apps/
          
          # Wait for deployments to roll out
          kubectl -n default rollout status deployment/frontend
          kubectl -n default rollout status deployment/backend

      - name: Verify deployments
        run: |
          echo "Checking deployment status..."
          kubectl get deployments
          
          echo "Checking pods status..."
          kubectl get pods
